### ISSUE TITLE
安装的时候运行 npm run watch 时报错

### ISSUE THREAD

**Issue by shencongcong** [tianyong90/willshop#5]
![image](https://user-images.githubusercontent.com/17448136/28460732-e82f0bcc-6e45-11e7-8b45-bc0fb1017518.png)
![image](https://user-images.githubusercontent.com/17448136/28460759-00110f42-6e46-11e7-9525-3237f9084dd9.png)

这是什么原因呢？

**Comment by tianyong90** [comment]
这是由于webpack里对scss文件相关的加载规则配置引起的。
尝试更新 laravel-mix 到最新版本，然后删除 webpack.mix.js 文件中如下图所示的这行再试。laravel-mix 更新非常快而对于 scss 文件加载规则是否内置变化多次，这一问题我随后会修正。

另外，这一项目是个人业余试验性的项目，部分功能还未完成，可能没法直接拿来用，当然如有兴趣，不妨当作参考。 😄 
![image](https://user-images.githubusercontent.com/9278461/28479260-40b430fe-6e8e-11e7-96e1-43c35828da8b.png)

**Comment by tianyong90** [comment]
刚把开发分支上最近的一些修改合并到主分支了，可以更新后再试。

**Comment by shencongcong** [comment]
ok
